# .github/workflows/deploy.yml
name: Deploy Astro to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm i --no-audit --progress=false
          fi

      - name: Configure Pages (auto-enable)
        uses: actions/configure-pages@v5
        with:
          enablement: true

      - name: Build (Astro)
        env:
          # For project pages (https://user.github.io/<repo>/), set repo Action Variable BASE_PATH="/<repo>/"
          BASE: ${{ vars.BASE_PATH }}
        run: |
          echo "BASE='$BASE'"
          npm run build
          touch dist/.nojekyll  # extra insurance: disable Jekyll on the artifact

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
